//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNesta.Coyote.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Carteira {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carteira() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNesta.Coyote.Web.App_GlobalResources.Carteira", typeof(Carteira).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira.
        /// </summary>
        public static string Field2 {
            get {
                return ResourceManager.GetString("Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Reduzido.
        /// </summary>
        public static string Field3 {
            get {
                return ResourceManager.GetString("Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira.
        /// </summary>
        public static string gridCol1 {
            get {
                return ResourceManager.GetString("gridCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Reduzida.
        /// </summary>
        public static string gridCol2 {
            get {
                return ResourceManager.GetString("gridCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string gridCol3 {
            get {
                return ResourceManager.GetString("gridCol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string gridCol4 {
            get {
                return ResourceManager.GetString("gridCol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listagem das carteiras disponíveis.
        /// </summary>
        public static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir a Carteira selecionada.
        /// </summary>
        public static string PageSubTitleDelete {
            get {
                return ResourceManager.GetString("PageSubTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar a Carteira selecionada.
        /// </summary>
        public static string PageSubTitleEdit {
            get {
                return ResourceManager.GetString("PageSubTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir uma Carteira.
        /// </summary>
        public static string PageSubTitleInsert {
            get {
                return ResourceManager.GetString("PageSubTitleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carteira.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Carteira.
        /// </summary>
        public static string SearchingPlaceHolder {
            get {
                return ResourceManager.GetString("SearchingPlaceHolder", resourceCulture);
            }
        }
    }
}
