//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNesta.Coyote.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Component {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Component() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNesta.Coyote.Web.App_GlobalResources.Component", typeof(Component).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string form_classe {
            get {
                return ResourceManager.GetString("form-classe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string form_component {
            get {
                return ResourceManager.GetString("form-component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string form_modelo {
            get {
                return ResourceManager.GetString("form-modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill the fields.
        /// </summary>
        public static string frm_validacao_preencha_campos {
            get {
                return ResourceManager.GetString("frm-validacao-preencha-campos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string grid_acao {
            get {
                return ResourceManager.GetString("grid-acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string grid_classe {
            get {
                return ResourceManager.GetString("grid-classe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string grid_componente {
            get {
                return ResourceManager.GetString("grid-componente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string grid_exportar {
            get {
                return ResourceManager.GetString("grid-exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string grid_id {
            get {
                return ResourceManager.GetString("grid-id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string grid_update {
            get {
                return ResourceManager.GetString("grid-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string header_component {
            get {
                return ResourceManager.GetString("header-component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component List.
        /// </summary>
        public static string header_subtitle_component {
            get {
                return ResourceManager.GetString("header-subtitle-component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum.
        /// </summary>
        public static string page_sub_title {
            get {
                return ResourceManager.GetString("page-sub-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        public static string page_title {
            get {
                return ResourceManager.GetString("page-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component List.
        /// </summary>
        public static string page_title_desc {
            get {
                return ResourceManager.GetString("page-title-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Component.
        /// </summary>
        public static string tooltip_txt_pesqcomp {
            get {
                return ResourceManager.GetString("tooltip_txt_pesqcomp", resourceCulture);
            }
        }
    }
}
