//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNesta.Coyote.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNesta.Coyote.Web.App_GlobalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string alert_fail {
            get {
                return ResourceManager.GetString("alert_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Captcha.
        /// </summary>
        public static string alert_fail_sub {
            get {
                return ResourceManager.GetString("alert_fail_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string alert_success {
            get {
                return ResourceManager.GetString("alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string alert_success_sub {
            get {
                return ResourceManager.GetString("alert_success_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_alterar {
            get {
                return ResourceManager.GetString("btn_alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancelar {
            get {
                return ResourceManager.GetString("btn_cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult.
        /// </summary>
        public static string btn_consultar {
            get {
                return ResourceManager.GetString("btn_consultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        public static string btn_desvincular {
            get {
                return ResourceManager.GetString("btn_desvincular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_excluir {
            get {
                return ResourceManager.GetString("btn_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        public static string btn_excluir_second {
            get {
                return ResourceManager.GetString("btn_excluir_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_grid_batch_cancel {
            get {
                return ResourceManager.GetString("btn_grid_batch_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted values.
        /// </summary>
        public static string btn_grid_batch_deletevalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_deletevalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide preview.
        /// </summary>
        public static string btn_grid_batch_hide {
            get {
                return ResourceManager.GetString("btn_grid_batch_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted values.
        /// </summary>
        public static string btn_grid_batch_insertvalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_insertvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string btn_grid_batch_preview {
            get {
                return ResourceManager.GetString("btn_grid_batch_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_grid_batch_save {
            get {
                return ResourceManager.GetString("btn_grid_batch_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated values.
        /// </summary>
        public static string btn_grid_batch_updatevalues {
            get {
                return ResourceManager.GetString("btn_grid_batch_updatevalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic.
        /// </summary>
        public static string btn_historico {
            get {
                return ResourceManager.GetString("btn_historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string btn_inserir {
            get {
                return ResourceManager.GetString("btn_inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string btn_processar {
            get {
                return ResourceManager.GetString("btn_processar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate.
        /// </summary>
        public static string btn_replicar {
            get {
                return ResourceManager.GetString("btn_replicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_salvar {
            get {
                return ResourceManager.GetString("btn_salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btn_selecionar {
            get {
                return ResourceManager.GetString("btn_selecionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string btn_vincular {
            get {
                return ResourceManager.GetString("btn_vincular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string btn_voltar {
            get {
                return ResourceManager.GetString("btn_voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Trading Base.
        /// </summary>
        public static string loadingpanel_basesnegociacao {
            get {
                return ResourceManager.GetString("loadingpanel_basesnegociacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Parameterization.
        /// </summary>
        public static string loadingpanel_basesnegociacao2 {
            get {
                return ResourceManager.GetString("loadingpanel_basesnegociacao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since:.
        /// </summary>
        public static string login_date {
            get {
                return ResourceManager.GetString("login_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language:.
        /// </summary>
        public static string login_language {
            get {
                return ResourceManager.GetString("login_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login User:.
        /// </summary>
        public static string login_user {
            get {
                return ResourceManager.GetString("login_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Typology.
        /// </summary>
        public static string menu_actions_lbl_01 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterparty.
        /// </summary>
        public static string menu_actions_lbl_02 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Class.
        /// </summary>
        public static string menu_actions_lbl_03 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string menu_actions_lbl_04 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexers.
        /// </summary>
        public static string menu_actions_lbl_05 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds.
        /// </summary>
        public static string menu_actions_lbl_06 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulas.
        /// </summary>
        public static string menu_actions_lbl_07 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        public static string menu_actions_lbl_08 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string menu_actions_lbl_09 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string menu_actions_lbl_10 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Layout.
        /// </summary>
        public static string menu_actions_lbl_11 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Readings.
        /// </summary>
        public static string menu_actions_lbl_12 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string menu_actions_lbl_13 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve ETTJ.
        /// </summary>
        public static string menu_actions_lbl_14 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string menu_actions_lbl_15 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string menu_actions_lbl_16 {
            get {
                return ResourceManager.GetString("menu_actions_lbl_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access our website.
        /// </summary>
        public static string menu_links_lbl_1 {
            get {
                return ResourceManager.GetString("menu_links_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webnesta.com.
        /// </summary>
        public static string menu_links_lbl_2 {
            get {
                return ResourceManager.GetString("menu_links_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on social networks.
        /// </summary>
        public static string menu_links_lbl_3 {
            get {
                return ResourceManager.GetString("menu_links_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string menu_profile_lbl_1 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string menu_profile_lbl_2 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ({0}).
        /// </summary>
        public static string menu_profile_lbl_3 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string menu_profile_lbl_4_1 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string menu_profile_lbl_4_2 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string menu_profile_lbl_5 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string menu_profile_lbl_6 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string menu_profile_lbl_7 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string menu_profile_lbl_8 {
            get {
                return ResourceManager.GetString("menu_profile_lbl_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}.
        /// </summary>
        public static string menu_profile_lbl_title_profile {
            get {
                return ResourceManager.GetString("menu_profile_lbl_title_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Tutorials.
        /// </summary>
        public static string menu_tutorial_lbl1 {
            get {
                return ResourceManager.GetString("menu_tutorial_lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5511995543452.
        /// </summary>
        public static string numero_nestabot {
            get {
                return ResourceManager.GetString("numero_nestabot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string tooltip_btn_action {
            get {
                return ResourceManager.GetString("tooltip_btn_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string tooltip_btn_editar {
            get {
                return ResourceManager.GetString("tooltip_btn_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string tooltip_btn_excluir {
            get {
                return ResourceManager.GetString("tooltip_btn_excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string tooltip_btn_links {
            get {
                return ResourceManager.GetString("tooltip_btn_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpDesk.
        /// </summary>
        public static string tooltip_btn_nestabot {
            get {
                return ResourceManager.GetString("tooltip_btn_nestabot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string tooltip_btn_novo {
            get {
                return ResourceManager.GetString("tooltip_btn_novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string tooltip_btn_tutorial {
            get {
                return ResourceManager.GetString("tooltip_btn_tutorial", resourceCulture);
            }
        }
    }
}
