//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNesta.Coyote.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNesta.Coyote.Web.App_GlobalResources.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Need Help.
        /// </summary>
        public static string label_1 {
            get {
                return ResourceManager.GetString("label_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        public static string label_10 {
            get {
                return ResourceManager.GetString("label_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email for.
        /// </summary>
        public static string label_11 {
            get {
                return ResourceManager.GetString("label_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recover your password.
        /// </summary>
        public static string label_12 {
            get {
                return ResourceManager.GetString("label_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string label_13 {
            get {
                return ResourceManager.GetString("label_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string label_14 {
            get {
                return ResourceManager.GetString("label_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string label_15 {
            get {
                return ResourceManager.GetString("label_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Guide - Login.
        /// </summary>
        public static string label_16 {
            get {
                return ResourceManager.GetString("label_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string label_2 {
            get {
                return ResourceManager.GetString("label_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string label_3 {
            get {
                return ResourceManager.GetString("label_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string label_4 {
            get {
                return ResourceManager.GetString("label_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string label_5 {
            get {
                return ResourceManager.GetString("label_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover my password.
        /// </summary>
        public static string label_6 {
            get {
                return ResourceManager.GetString("label_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string label_7 {
            get {
                return ResourceManager.GetString("label_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code from above.
        /// </summary>
        public static string label_8 {
            get {
                return ResourceManager.GetString("label_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved for Somnium Tecnologia S. A..
        /// </summary>
        public static string label_9 {
            get {
                return ResourceManager.GetString("label_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code from above:.
        /// </summary>
        public static string label_captcha_1 {
            get {
                return ResourceManager.GetString("label_captcha_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código incorreto..
        /// </summary>
        public static string label_captcha_2 {
            get {
                return ResourceManager.GetString("label_captcha_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator.
        /// </summary>
        public static string label_google_1 {
            get {
                return ResourceManager.GetString("label_google_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the Google app.
        /// </summary>
        public static string label_google_2 {
            get {
                return ResourceManager.GetString("label_google_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator on your mobile phone and scan the QR code below.
        /// </summary>
        public static string label_google_3 {
            get {
                return ResourceManager.GetString("label_google_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string label_google_4 {
            get {
                return ResourceManager.GetString("label_google_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string tooltip_btn_action {
            get {
                return ResourceManager.GetString("tooltip_btn_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captcha code field entered is different..
        /// </summary>
        public static string validacao_CampoCodigoCaptchaInformadoDiferente {
            get {
                return ResourceManager.GetString("validacao_CampoCodigoCaptchaInformadoDiferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code field must be filled in..
        /// </summary>
        public static string validacao_CampoCodigoDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_CampoCodigoDeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security code field must be filled in..
        /// </summary>
        public static string validacao_CampoCodigoSegurancaDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_CampoCodigoSegurancaDeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be filled..
        /// </summary>
        public static string validacao_CodigoDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_CodigoDeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be filled..
        /// </summary>
        public static string validacao_EmailDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_EmailDeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string validacao_Entrar {
            get {
                return ResourceManager.GetString("validacao_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string validacao_FormatoEmailInvalido {
            get {
                return ResourceManager.GetString("validacao_FormatoEmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string validacao_Proximo {
            get {
                return ResourceManager.GetString("validacao_Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User, Password and Code must be filled..
        /// </summary>
        public static string validacao_UsuarioSenhaCodigoDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_UsuarioSenhaCodigoDeveSerPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and Password must be filled..
        /// </summary>
        public static string validacao_UsuarioSenhaDeveSerPreenchido {
            get {
                return ResourceManager.GetString("validacao_UsuarioSenhaDeveSerPreenchido", resourceCulture);
            }
        }
    }
}
