//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Carteira {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Carteira() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Carteira", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        internal static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Carteira.
        /// </summary>
        internal static string Field2 {
            get {
                return ResourceManager.GetString("Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome Reduzido.
        /// </summary>
        internal static string Field3 {
            get {
                return ResourceManager.GetString("Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Carteira.
        /// </summary>
        internal static string gridCol1 {
            get {
                return ResourceManager.GetString("gridCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição Reduzida.
        /// </summary>
        internal static string gridCol2 {
            get {
                return ResourceManager.GetString("gridCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        internal static string gridCol3 {
            get {
                return ResourceManager.GetString("gridCol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ações.
        /// </summary>
        internal static string gridCol4 {
            get {
                return ResourceManager.GetString("gridCol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Listagem das carteiras disponíveis.
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Excluir a Carteira selecionada.
        /// </summary>
        internal static string PageSubTitleDelete {
            get {
                return ResourceManager.GetString("PageSubTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Alterar a Carteira selecionada.
        /// </summary>
        internal static string PageSubTitleEdit {
            get {
                return ResourceManager.GetString("PageSubTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inserir uma Carteira.
        /// </summary>
        internal static string PageSubTitleInsert {
            get {
                return ResourceManager.GetString("PageSubTitleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Carteira.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pesquisar Carteira.
        /// </summary>
        internal static string SearchingPlaceHolder {
            get {
                return ResourceManager.GetString("SearchingPlaceHolder", resourceCulture);
            }
        }
    }
}
