//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fornecedores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fornecedores() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Fornecedores", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Empresa.
        /// </summary>
        internal static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contato - Nome.
        /// </summary>
        internal static string Field10 {
            get {
                return ResourceManager.GetString("Field10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contato - Email.
        /// </summary>
        internal static string Field11 {
            get {
                return ResourceManager.GetString("Field11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contato - Whatsapp.
        /// </summary>
        internal static string Field12 {
            get {
                return ResourceManager.GetString("Field12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Chave Pix.
        /// </summary>
        internal static string Field13 {
            get {
                return ResourceManager.GetString("Field13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ID - Fornecedor.
        /// </summary>
        internal static string Field2 {
            get {
                return ResourceManager.GetString("Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Razão Social.
        /// </summary>
        internal static string Field3 {
            get {
                return ResourceManager.GetString("Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Destino Remessa.
        /// </summary>
        internal static string Field4 {
            get {
                return ResourceManager.GetString("Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome Reduzido.
        /// </summary>
        internal static string Field5 {
            get {
                return ResourceManager.GetString("Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a País.
        /// </summary>
        internal static string Field6 {
            get {
                return ResourceManager.GetString("Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Banco.
        /// </summary>
        internal static string Field7 {
            get {
                return ResourceManager.GetString("Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Agência.
        /// </summary>
        internal static string Field8 {
            get {
                return ResourceManager.GetString("Field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conta.
        /// </summary>
        internal static string Field9 {
            get {
                return ResourceManager.GetString("Field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sub Texto Fornecedores.
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sub Texto Consultar Fornecedores.
        /// </summary>
        internal static string PageSubTitleConsult {
            get {
                return ResourceManager.GetString("PageSubTitleConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sub Texto Excluir Fornecedores.
        /// </summary>
        internal static string PageSubTitleDelete {
            get {
                return ResourceManager.GetString("PageSubTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sub Texto Alterar Fornecedores.
        /// </summary>
        internal static string PageSubTitleEdit {
            get {
                return ResourceManager.GetString("PageSubTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sub Texto Inserir Fornecedores.
        /// </summary>
        internal static string PageSubTitleInsert {
            get {
                return ResourceManager.GetString("PageSubTitleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contraparte.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a #ID.
        /// </summary>
        internal static string SearchingCol1 {
            get {
                return ResourceManager.GetString("SearchingCol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Razão Social.
        /// </summary>
        internal static string SearchingCol2 {
            get {
                return ResourceManager.GetString("SearchingCol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pesquisar Contraparte.
        /// </summary>
        internal static string SearchingPlaceHolder {
            get {
                return ResourceManager.GetString("SearchingPlaceHolder", resourceCulture);
            }
        }
    }
}
