//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Verbas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Verbas() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Verbas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verba.
        /// </summary>
        internal static string field1 {
            get {
                return ResourceManager.GetString("field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tolerância %.
        /// </summary>
        internal static string field10 {
            get {
                return ResourceManager.GetString("field10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Base Cálculo Meses.
        /// </summary>
        internal static string field11 {
            get {
                return ResourceManager.GetString("field11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Formato.
        /// </summary>
        internal static string field12 {
            get {
                return ResourceManager.GetString("field12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Saída.
        /// </summary>
        internal static string field12_1 {
            get {
                return ResourceManager.GetString("field12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Entrada.
        /// </summary>
        internal static string field12_2 {
            get {
                return ResourceManager.GetString("field12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calcula IFRS?.
        /// </summary>
        internal static string field2 {
            get {
                return ResourceManager.GetString("field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string field2_1 {
            get {
                return ResourceManager.GetString("field2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string field2_2 {
            get {
                return ResourceManager.GetString("field2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Classificador.
        /// </summary>
        internal static string field3 {
            get {
                return ResourceManager.GetString("field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo Verbas.
        /// </summary>
        internal static string field4 {
            get {
                return ResourceManager.GetString("field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Acessória.
        /// </summary>
        internal static string field4_1 {
            get {
                return ResourceManager.GetString("field4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contratada.
        /// </summary>
        internal static string field4_2 {
            get {
                return ResourceManager.GetString("field4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Periodicidade.
        /// </summary>
        internal static string field5 {
            get {
                return ResourceManager.GetString("field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Mensal.
        /// </summary>
        internal static string field5_1 {
            get {
                return ResourceManager.GetString("field5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Bimestral.
        /// </summary>
        internal static string field5_2 {
            get {
                return ResourceManager.GetString("field5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Trimestral.
        /// </summary>
        internal static string field5_3 {
            get {
                return ResourceManager.GetString("field5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Quadrimestral.
        /// </summary>
        internal static string field5_4 {
            get {
                return ResourceManager.GetString("field5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Semestral.
        /// </summary>
        internal static string field5_5 {
            get {
                return ResourceManager.GetString("field5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Anual.
        /// </summary>
        internal static string field5_6 {
            get {
                return ResourceManager.GetString("field5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Recuperação de Impostos.
        /// </summary>
        internal static string field6 {
            get {
                return ResourceManager.GetString("field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string field6_1 {
            get {
                return ResourceManager.GetString("field6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string field6_2 {
            get {
                return ResourceManager.GetString("field6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Intervalo.
        /// </summary>
        internal static string field7 {
            get {
                return ResourceManager.GetString("field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Eventual.
        /// </summary>
        internal static string field7_1 {
            get {
                return ResourceManager.GetString("field7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Permanente.
        /// </summary>
        internal static string field7_2 {
            get {
                return ResourceManager.GetString("field7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modo Valor.
        /// </summary>
        internal static string field8 {
            get {
                return ResourceManager.GetString("field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informada.
        /// </summary>
        internal static string field8_1 {
            get {
                return ResourceManager.GetString("field8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calculada.
        /// </summary>
        internal static string field8_2 {
            get {
                return ResourceManager.GetString("field8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Calcula Imposto?.
        /// </summary>
        internal static string field9 {
            get {
                return ResourceManager.GetString("field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string field9_1 {
            get {
                return ResourceManager.GetString("field9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string field9_2 {
            get {
                return ResourceManager.GetString("field9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Eventual.
        /// </summary>
        internal static string fieldl7_1 {
            get {
                return ResourceManager.GetString("fieldl7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verba.
        /// </summary>
        internal static string grid_col_1 {
            get {
                return ResourceManager.GetString("grid_col-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a IFRS?.
        /// </summary>
        internal static string grid_col_2 {
            get {
                return ResourceManager.GetString("grid_col-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo Receita.
        /// </summary>
        internal static string grid_col_3 {
            get {
                return ResourceManager.GetString("grid_col-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione....
        /// </summary>
        internal static string nullField {
            get {
                return ResourceManager.GetString("nullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Subtitulo.
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string PageSubTitleDelete {
            get {
                return ResourceManager.GetString("PageSubTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        internal static string PageSubTitleEdit {
            get {
                return ResourceManager.GetString("PageSubTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Inserir.
        /// </summary>
        internal static string PageSubTitleInsert {
            get {
                return ResourceManager.GetString("PageSubTitleInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Verbas.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pesquisar Verba.
        /// </summary>
        internal static string SearchingField {
            get {
                return ResourceManager.GetString("SearchingField", resourceCulture);
            }
        }
    }
}
