//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CapaContrato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CapaContrato() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CapaContrato", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Cover.
        /// </summary>
        internal static string accordion_1 {
            get {
                return ResourceManager.GetString("accordion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a View Contracts.
        /// </summary>
        internal static string accordion_1_btn_1 {
            get {
                return ResourceManager.GetString("accordion_1_btn_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        internal static string accordion_1_field_1 {
            get {
                return ResourceManager.GetString("accordion_1_field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closing Date.
        /// </summary>
        internal static string accordion_1_field_10 {
            get {
                return ResourceManager.GetString("accordion_1_field_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Manager.
        /// </summary>
        internal static string accordion_1_field_11 {
            get {
                return ResourceManager.GetString("accordion_1_field_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nominal value.
        /// </summary>
        internal static string accordion_1_field_12 {
            get {
                return ResourceManager.GetString("accordion_1_field_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Supervisor.
        /// </summary>
        internal static string accordion_1_field_13 {
            get {
                return ResourceManager.GetString("accordion_1_field_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Counterparty.
        /// </summary>
        internal static string accordion_1_field_14 {
            get {
                return ResourceManager.GetString("accordion_1_field_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Condition.
        /// </summary>
        internal static string accordion_1_field_15 {
            get {
                return ResourceManager.GetString("accordion_1_field_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string accordion_1_field_16 {
            get {
                return ResourceManager.GetString("accordion_1_field_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string accordion_1_field_17 {
            get {
                return ResourceManager.GetString("accordion_1_field_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Internal ID.
        /// </summary>
        internal static string accordion_1_field_2 {
            get {
                return ResourceManager.GetString("accordion_1_field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Number.
        /// </summary>
        internal static string accordion_1_field_3 {
            get {
                return ResourceManager.GetString("accordion_1_field_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Surname.
        /// </summary>
        internal static string accordion_1_field_4 {
            get {
                return ResourceManager.GetString("accordion_1_field_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auxiliary Number.
        /// </summary>
        internal static string accordion_1_field_5 {
            get {
                return ResourceManager.GetString("accordion_1_field_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Segment.
        /// </summary>
        internal static string accordion_1_field_6 {
            get {
                return ResourceManager.GetString("accordion_1_field_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string accordion_1_field_7 {
            get {
                return ResourceManager.GetString("accordion_1_field_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date Signature.
        /// </summary>
        internal static string accordion_1_field_8 {
            get {
                return ResourceManager.GetString("accordion_1_field_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Start Date.
        /// </summary>
        internal static string accordion_1_field_9 {
            get {
                return ResourceManager.GetString("accordion_1_field_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Trading Basis.
        /// </summary>
        internal static string accordion_2 {
            get {
                return ResourceManager.GetString("accordion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Fronts.
        /// </summary>
        internal static string accordion_3 {
            get {
                return ResourceManager.GetString("accordion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string accordion_3_col_1 {
            get {
                return ResourceManager.GetString("accordion_3_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Start Date.
        /// </summary>
        internal static string accordion_3_col_2 {
            get {
                return ResourceManager.GetString("accordion_3_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string accordion_3_col_3 {
            get {
                return ResourceManager.GetString("accordion_3_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a General information.
        /// </summary>
        internal static string accordion_4 {
            get {
                return ResourceManager.GetString("accordion_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Type.
        /// </summary>
        internal static string accordion_4_field1 {
            get {
                return ResourceManager.GetString("accordion_4_field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closing Date.
        /// </summary>
        internal static string accordion_4_field10 {
            get {
                return ResourceManager.GetString("accordion_4_field10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Value.
        /// </summary>
        internal static string accordion_4_field11 {
            get {
                return ResourceManager.GetString("accordion_4_field11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Counterparty.
        /// </summary>
        internal static string accordion_4_field12 {
            get {
                return ResourceManager.GetString("accordion_4_field12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string accordion_4_field13 {
            get {
                return ResourceManager.GetString("accordion_4_field13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Internal ID.
        /// </summary>
        internal static string accordion_4_field2 {
            get {
                return ResourceManager.GetString("accordion_4_field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Father ID.
        /// </summary>
        internal static string accordion_4_field3 {
            get {
                return ResourceManager.GetString("accordion_4_field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nickname.
        /// </summary>
        internal static string accordion_4_field4 {
            get {
                return ResourceManager.GetString("accordion_4_field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Typology.
        /// </summary>
        internal static string accordion_4_field5 {
            get {
                return ResourceManager.GetString("accordion_4_field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Portfolio.
        /// </summary>
        internal static string accordion_4_field6 {
            get {
                return ResourceManager.GetString("accordion_4_field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string accordion_4_field7 {
            get {
                return ResourceManager.GetString("accordion_4_field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data Base.
        /// </summary>
        internal static string accordion_4_field8 {
            get {
                return ResourceManager.GetString("accordion_4_field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Start Date.
        /// </summary>
        internal static string accordion_4_field9 {
            get {
                return ResourceManager.GetString("accordion_4_field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adjust Contract Balance?.
        /// </summary>
        internal static string addition_popup_check {
            get {
                return ResourceManager.GetString("addition_popup_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Historic.
        /// </summary>
        internal static string addition_popup_hist {
            get {
                return ResourceManager.GetString("addition_popup_hist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Start Date.
        /// </summary>
        internal static string addition_popup_input1 {
            get {
                return ResourceManager.GetString("addition_popup_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string addition_popup_input2 {
            get {
                return ResourceManager.GetString("addition_popup_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Base Date.
        /// </summary>
        internal static string addition_popup_input3 {
            get {
                return ResourceManager.GetString("addition_popup_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Value.
        /// </summary>
        internal static string addition_popup_input4 {
            get {
                return ResourceManager.GetString("addition_popup_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Justification.
        /// </summary>
        internal static string addition_popup_input5 {
            get {
                return ResourceManager.GetString("addition_popup_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enter the addition information for the selected front.
        /// </summary>
        internal static string addition_popup_sub_title {
            get {
                return ResourceManager.GetString("addition_popup_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Addendum.
        /// </summary>
        internal static string addition_popup_title {
            get {
                return ResourceManager.GetString("addition_popup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Front.
        /// </summary>
        internal static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insert Contract.
        /// </summary>
        internal static string btn2 {
            get {
                return ResourceManager.GetString("btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirm Deletion.
        /// </summary>
        internal static string btn_delete_2 {
            get {
                return ResourceManager.GetString("btn_delete_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Current Balance.
        /// </summary>
        internal static string current_balance {
            get {
                return ResourceManager.GetString("current_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Upload Agreement.
        /// </summary>
        internal static string files_popup_btn1 {
            get {
                return ResourceManager.GetString("files_popup_btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select a file to the side to view.
        /// </summary>
        internal static string files_popup_empty {
            get {
                return ResourceManager.GetString("files_popup_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Download.
        /// </summary>
        internal static string files_popup_link1 {
            get {
                return ResourceManager.GetString("files_popup_link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string files_popup_link2 {
            get {
                return ResourceManager.GetString("files_popup_link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts.
        /// </summary>
        internal static string files_popup_title {
            get {
                return ResourceManager.GetString("files_popup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File Preview.
        /// </summary>
        internal static string files_popup_title2 {
            get {
                return ResourceManager.GetString("files_popup_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Addition.
        /// </summary>
        internal static string front_grid_addition {
            get {
                return ResourceManager.GetString("front_grid_addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Alter.
        /// </summary>
        internal static string front_grid_alter {
            get {
                return ResourceManager.GetString("front_grid_alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string front_grid_delete {
            get {
                return ResourceManager.GetString("front_grid_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Justification.
        /// </summary>
        internal static string grid_aditamentos_col1 {
            get {
                return ResourceManager.GetString("grid_aditamentos_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Negotiated Basis.
        /// </summary>
        internal static string grid_aditamentos_col2 {
            get {
                return ResourceManager.GetString("grid_aditamentos_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Changed Value.
        /// </summary>
        internal static string grid_aditamentos_col3 {
            get {
                return ResourceManager.GetString("grid_aditamentos_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        internal static string grid_aditamentos_col4 {
            get {
                return ResourceManager.GetString("grid_aditamentos_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a No Amendment History.
        /// </summary>
        internal static string grid_aditamentos_empty {
            get {
                return ResourceManager.GetString("grid_aditamentos_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delete.
        /// </summary>
        internal static string popup_delete {
            get {
                return ResourceManager.GetString("popup_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Download.
        /// </summary>
        internal static string popup_download {
            get {
                return ResourceManager.GetString("popup_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select a file to the side to view.
        /// </summary>
        internal static string popup_guide {
            get {
                return ResourceManager.GetString("popup_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a File preview.
        /// </summary>
        internal static string popup_sub_title {
            get {
                return ResourceManager.GetString("popup_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts.
        /// </summary>
        internal static string popup_title {
            get {
                return ResourceManager.GetString("popup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Upload.
        /// </summary>
        internal static string popup_upload_btn {
            get {
                return ResourceManager.GetString("popup_upload_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Auxiliary Code.
        /// </summary>
        internal static string search_auxiliary_code {
            get {
                return ResourceManager.GetString("search_auxiliary_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string search_description {
            get {
                return ResourceManager.GetString("search_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search Contract.
        /// </summary>
        internal static string search_field {
            get {
                return ResourceManager.GetString("search_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Process No..
        /// </summary>
        internal static string search_process_num {
            get {
                return ResourceManager.GetString("search_process_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Search or insert a contract.
        /// </summary>
        internal static string sub_title {
            get {
                return ResourceManager.GetString("sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Manage the selected contract.
        /// </summary>
        internal static string sub_title_consultation {
            get {
                return ResourceManager.GetString("sub_title_consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirm the contract deletion.
        /// </summary>
        internal static string sub_title_delete {
            get {
                return ResourceManager.GetString("sub_title_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Change the selected contract.
        /// </summary>
        internal static string sub_title_edit {
            get {
                return ResourceManager.GetString("sub_title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Manage the selected contract front.
        /// </summary>
        internal static string sub_title_front_consultation {
            get {
                return ResourceManager.GetString("sub_title_front_consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirm the deletion of the contractual front.
        /// </summary>
        internal static string sub_title_front_delete {
            get {
                return ResourceManager.GetString("sub_title_front_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Change the selected contract front.
        /// </summary>
        internal static string sub_title_front_edit {
            get {
                return ResourceManager.GetString("sub_title_front_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insert a contract front record.
        /// </summary>
        internal static string sub_title_front_insert {
            get {
                return ResourceManager.GetString("sub_title_front_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enter a contract record.
        /// </summary>
        internal static string sub_title_insert {
            get {
                return ResourceManager.GetString("sub_title_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Registration.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
