//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClasseContabil {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClasseContabil() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ClasseContabil", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string field_1 {
            get {
                return ResourceManager.GetString("field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verba.
        /// </summary>
        internal static string field_2 {
            get {
                return ResourceManager.GetString("field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Crédito.
        /// </summary>
        internal static string field_3 {
            get {
                return ResourceManager.GetString("field_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Débito.
        /// </summary>
        internal static string field_4 {
            get {
                return ResourceManager.GetString("field_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string field_main {
            get {
                return ResourceManager.GetString("field_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verba.
        /// </summary>
        internal static string grid_col1 {
            get {
                return ResourceManager.GetString("grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito.
        /// </summary>
        internal static string grid_col2 {
            get {
                return ResourceManager.GetString("grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débito.
        /// </summary>
        internal static string grid_col3 {
            get {
                return ResourceManager.GetString("grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        internal static string grid_col4 {
            get {
                return ResourceManager.GetString("grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string grid_col5 {
            get {
                return ResourceManager.GetString("grid_col5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string PageSubTitle_Alterar {
            get {
                return ResourceManager.GetString("PageSubTitle_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string PageSubTitle_Excluir {
            get {
                return ResourceManager.GetString("PageSubTitle_Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir.
        /// </summary>
        internal static string PageSubTitle_Inserir {
            get {
                return ResourceManager.GetString("PageSubTitle_Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe Contabil.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Verba.
        /// </summary>
        internal static string SearchingField {
            get {
                return ResourceManager.GetString("SearchingField", resourceCulture);
            }
        }
    }
}
