//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Formulas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formulas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Formulas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string grid_nav2_col_1 {
            get {
                return ResourceManager.GetString("grid_nav2_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string grid_nav2_col_1_item_1 {
            get {
                return ResourceManager.GetString("grid_nav2_col_1_item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        internal static string grid_nav2_col_1_item_2 {
            get {
                return ResourceManager.GetString("grid_nav2_col_1_item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento.
        /// </summary>
        internal static string grid_nav2_col_1_item_3 {
            get {
                return ResourceManager.GetString("grid_nav2_col_1_item_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual.
        /// </summary>
        internal static string grid_nav2_col_2 {
            get {
                return ResourceManager.GetString("grid_nav2_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias.
        /// </summary>
        internal static string grid_nav2_col_3 {
            get {
                return ResourceManager.GetString("grid_nav2_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexador.
        /// </summary>
        internal static string grid_nav2_col_4 {
            get {
                return ResourceManager.GetString("grid_nav2_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string grid_search_col_1 {
            get {
                return ResourceManager.GetString("grid_search_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        internal static string grid_search_col_2 {
            get {
                return ResourceManager.GetString("grid_search_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula de Reajuste.
        /// </summary>
        internal static string Nav_1 {
            get {
                return ResourceManager.GetString("Nav_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Nav_1_field_1 {
            get {
                return ResourceManager.GetString("Nav_1_field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string Nav_1_field_2 {
            get {
                return ResourceManager.GetString("Nav_1_field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string Nav_1_field_3 {
            get {
                return ResourceManager.GetString("Nav_1_field_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexador.
        /// </summary>
        internal static string Nav_1_field_3_item_1 {
            get {
                return ResourceManager.GetString("Nav_1_field_3_item_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        internal static string Nav_1_field_3_item_2 {
            get {
                return ResourceManager.GetString("Nav_1_field_3_item_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmula.
        /// </summary>
        internal static string Nav_1_field_4 {
            get {
                return ResourceManager.GetString("Nav_1_field_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variáveis.
        /// </summary>
        internal static string Nav_2 {
            get {
                return ResourceManager.GetString("Nav_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle_Alterar {
            get {
                return ResourceManager.GetString("PageSubTitle_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle_Consulta {
            get {
                return ResourceManager.GetString("PageSubTitle_Consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle_Excluir {
            get {
                return ResourceManager.GetString("PageSubTitle_Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir Lorem Ipsum.
        /// </summary>
        internal static string PageSubTitle_Inserir {
            get {
                return ResourceManager.GetString("PageSubTitle_Inserir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fórmulas.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Fórmulas.
        /// </summary>
        internal static string SearchingField {
            get {
                return ResourceManager.GetString("SearchingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar.
        /// </summary>
        internal static string test_button {
            get {
                return ResourceManager.GetString("test_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Base.
        /// </summary>
        internal static string test_popup_field_1 {
            get {
                return ResourceManager.GetString("test_popup_field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Evento.
        /// </summary>
        internal static string test_popup_field_2 {
            get {
                return ResourceManager.GetString("test_popup_field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Pagamento.
        /// </summary>
        internal static string test_popup_field_3 {
            get {
                return ResourceManager.GetString("test_popup_field_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string test_popup_field_4 {
            get {
                return ResourceManager.GetString("test_popup_field_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste Rápido.
        /// </summary>
        internal static string test_popup_header {
            get {
                return ResourceManager.GetString("test_popup_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar.
        /// </summary>
        internal static string test_popup_run_button {
            get {
                return ResourceManager.GetString("test_popup_run_button", resourceCulture);
            }
        }
    }
}
