//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Setup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company Bond.
        /// </summary>
        internal static string btn_company_link {
            get {
                return ResourceManager.GetString("btn_company_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Disable.
        /// </summary>
        internal static string btn_disable {
            get {
                return ResourceManager.GetString("btn_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Property.
        /// </summary>
        internal static string btn_dynprop {
            get {
                return ResourceManager.GetString("btn_dynprop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Enable.
        /// </summary>
        internal static string btn_enable {
            get {
                return ResourceManager.GetString("btn_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Event.
        /// </summary>
        internal static string btn_events {
            get {
                return ResourceManager.GetString("btn_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Parameterization.
        /// </summary>
        internal static string btn_parametrizacao {
            get {
                return ResourceManager.GetString("btn_parametrizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reset Password.
        /// </summary>
        internal static string btn_pass_reset {
            get {
                return ResourceManager.GetString("btn_pass_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Topology.
        /// </summary>
        internal static string btn_topology {
            get {
                return ResourceManager.GetString("btn_topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Linked Properties.
        /// </summary>
        internal static string dynprop_grid_title1 {
            get {
                return ResourceManager.GetString("dynprop_grid_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available Properties.
        /// </summary>
        internal static string dynprop_grid_title2 {
            get {
                return ResourceManager.GetString("dynprop_grid_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string dynprop_input1 {
            get {
                return ResourceManager.GetString("dynprop_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string dynprop_insert_input1 {
            get {
                return ResourceManager.GetString("dynprop_insert_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Validation.
        /// </summary>
        internal static string dynprop_insert_input10 {
            get {
                return ResourceManager.GetString("dynprop_insert_input10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Message.
        /// </summary>
        internal static string dynprop_insert_input11 {
            get {
                return ResourceManager.GetString("dynprop_insert_input11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Filter.
        /// </summary>
        internal static string dynprop_insert_input12 {
            get {
                return ResourceManager.GetString("dynprop_insert_input12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Property.
        /// </summary>
        internal static string dynprop_insert_input2 {
            get {
                return ResourceManager.GetString("dynprop_insert_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string dynprop_insert_input3 {
            get {
                return ResourceManager.GetString("dynprop_insert_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string dynprop_insert_input4 {
            get {
                return ResourceManager.GetString("dynprop_insert_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Feed Format.
        /// </summary>
        internal static string dynprop_insert_input5 {
            get {
                return ResourceManager.GetString("dynprop_insert_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Order.
        /// </summary>
        internal static string dynprop_insert_input6 {
            get {
                return ResourceManager.GetString("dynprop_insert_input6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Mandatory.
        /// </summary>
        internal static string dynprop_insert_input7 {
            get {
                return ResourceManager.GetString("dynprop_insert_input7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Visible.
        /// </summary>
        internal static string dynprop_insert_input8 {
            get {
                return ResourceManager.GetString("dynprop_insert_input8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Key.
        /// </summary>
        internal static string dynprop_insert_input9 {
            get {
                return ResourceManager.GetString("dynprop_insert_input9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Property - Delete.
        /// </summary>
        internal static string dynprop_screen_delete {
            get {
                return ResourceManager.GetString("dynprop_screen_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Property - Edit.
        /// </summary>
        internal static string dynprop_screen_edit {
            get {
                return ResourceManager.GetString("dynprop_screen_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Property - Insert.
        /// </summary>
        internal static string dynprop_screen_insert {
            get {
                return ResourceManager.GetString("dynprop_screen_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string events_input1 {
            get {
                return ResourceManager.GetString("events_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select the Event.
        /// </summary>
        internal static string event_input_null_text {
            get {
                return ResourceManager.GetString("event_input_null_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Fund.
        /// </summary>
        internal static string funds_btn {
            get {
                return ResourceManager.GetString("funds_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Modality.
        /// </summary>
        internal static string funds_grid_head1 {
            get {
                return ResourceManager.GetString("funds_grid_head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        internal static string funds_grid_head2 {
            get {
                return ResourceManager.GetString("funds_grid_head2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string funds_input1 {
            get {
                return ResourceManager.GetString("funds_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds - Change.
        /// </summary>
        internal static string funds_screen_edit {
            get {
                return ResourceManager.GetString("funds_screen_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds - Insert.
        /// </summary>
        internal static string funds_screen_insert {
            get {
                return ResourceManager.GetString("funds_screen_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string funds_screen_insert_input1 {
            get {
                return ResourceManager.GetString("funds_screen_insert_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Material.
        /// </summary>
        internal static string funds_screen_insert_input2 {
            get {
                return ResourceManager.GetString("funds_screen_insert_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Reference Value.
        /// </summary>
        internal static string funds_screen_insert_input3 {
            get {
                return ResourceManager.GetString("funds_screen_insert_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tolerance.
        /// </summary>
        internal static string funds_screen_insert_input4 {
            get {
                return ResourceManager.GetString("funds_screen_insert_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type of Fund.
        /// </summary>
        internal static string funds_screen_insert_input5 {
            get {
                return ResourceManager.GetString("funds_screen_insert_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Property.
        /// </summary>
        internal static string grid_dynprop_head {
            get {
                return ResourceManager.GetString("grid_dynprop_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Event.
        /// </summary>
        internal static string grid_events_head1 {
            get {
                return ResourceManager.GetString("grid_events_head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Country.
        /// </summary>
        internal static string grid_events_head2 {
            get {
                return ResourceManager.GetString("grid_events_head2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Linked Funds.
        /// </summary>
        internal static string grid_funds_title1 {
            get {
                return ResourceManager.GetString("grid_funds_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available Funds.
        /// </summary>
        internal static string grid_funds_title2 {
            get {
                return ResourceManager.GetString("grid_funds_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string grid_topology_action1 {
            get {
                return ResourceManager.GetString("grid_topology_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string grid_topology_head1 {
            get {
                return ResourceManager.GetString("grid_topology_head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string grid_topology_head2 {
            get {
                return ResourceManager.GetString("grid_topology_head2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Class.
        /// </summary>
        internal static string grid_topology_head3 {
            get {
                return ResourceManager.GetString("grid_topology_head3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Actions.
        /// </summary>
        internal static string grid_topology_head4 {
            get {
                return ResourceManager.GetString("grid_topology_head4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Manage Users.
        /// </summary>
        internal static string index_menu_1 {
            get {
                return ResourceManager.GetString("index_menu_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User registration.
        /// </summary>
        internal static string index_menu_1_subitem_1 {
            get {
                return ResourceManager.GetString("index_menu_1_subitem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Framework.
        /// </summary>
        internal static string index_menu_2 {
            get {
                return ResourceManager.GetString("index_menu_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Typology.
        /// </summary>
        internal static string index_menu_2_subitem_1 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events.
        /// </summary>
        internal static string index_menu_2_subitem_2 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dynamic Properties.
        /// </summary>
        internal static string index_menu_2_subitem_3 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds.
        /// </summary>
        internal static string index_menu_2_subitem_4 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Methods.
        /// </summary>
        internal static string index_menu_2_subitem_5 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Functions.
        /// </summary>
        internal static string index_menu_2_subitem_6 {
            get {
                return ResourceManager.GetString("index_menu_2_subitem_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        internal static string index_menu_3 {
            get {
                return ResourceManager.GetString("index_menu_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company Registration.
        /// </summary>
        internal static string index_menu_3_subitem_1 {
            get {
                return ResourceManager.GetString("index_menu_3_subitem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Licenses.
        /// </summary>
        internal static string index_menu_3_subitem_2 {
            get {
                return ResourceManager.GetString("index_menu_3_subitem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Stock Report.
        /// </summary>
        internal static string index_menu_4 {
            get {
                return ResourceManager.GetString("index_menu_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Registration.
        /// </summary>
        internal static string menu_1_screen_1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New User.
        /// </summary>
        internal static string menu_1_screen_1_btn {
            get {
                return ResourceManager.GetString("menu_1_screen_1_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        internal static string menu_1_screen_1_grid1_col1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid1_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Related Companies.
        /// </summary>
        internal static string menu_1_screen_1_grid1_title {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        internal static string menu_1_screen_1_grid2_col1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid2_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available Companies.
        /// </summary>
        internal static string menu_1_screen_1_grid2_title {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Profile.
        /// </summary>
        internal static string menu_1_screen_1_grid_col1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User.
        /// </summary>
        internal static string menu_1_screen_1_grid_col2 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string menu_1_screen_1_grid_col3 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid_col3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string menu_1_screen_1_grid_col4 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_grid_col4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string menu_1_screen_1_lbl_1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Last name.
        /// </summary>
        internal static string menu_1_screen_1_lbl_2 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        internal static string menu_1_screen_1_lbl_3 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cell.
        /// </summary>
        internal static string menu_1_screen_1_lbl_4 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string menu_1_screen_1_lbl_5 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Profile.
        /// </summary>
        internal static string menu_1_screen_1_lbl_6 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_lbl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Registration - Insert.
        /// </summary>
        internal static string menu_1_screen_1_subtitle1 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Registration - Change.
        /// </summary>
        internal static string menu_1_screen_1_subtitle2 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a User Registration - Companies.
        /// </summary>
        internal static string menu_1_screen_1_subtitle3 {
            get {
                return ResourceManager.GetString("menu_1_screen_1_subtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a New Method.
        /// </summary>
        internal static string methods_btn {
            get {
                return ResourceManager.GetString("methods_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Method.
        /// </summary>
        internal static string methods_grid_header1 {
            get {
                return ResourceManager.GetString("methods_grid_header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Linked Methods.
        /// </summary>
        internal static string methods_grid_title1 {
            get {
                return ResourceManager.GetString("methods_grid_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Available Methods.
        /// </summary>
        internal static string methods_grid_title2 {
            get {
                return ResourceManager.GetString("methods_grid_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Methods - Delete.
        /// </summary>
        internal static string methods_screen_delete {
            get {
                return ResourceManager.GetString("methods_screen_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Methods - Change.
        /// </summary>
        internal static string methods_screen_edit {
            get {
                return ResourceManager.GetString("methods_screen_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Methods - Insert.
        /// </summary>
        internal static string methods_screen_insert {
            get {
                return ResourceManager.GetString("methods_screen_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Type Method.
        /// </summary>
        internal static string method_insert_input {
            get {
                return ResourceManager.GetString("method_insert_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology must be selected first..
        /// </summary>
        internal static string msg_dynprop {
            get {
                return ResourceManager.GetString("msg_dynprop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds.
        /// </summary>
        internal static string parameterization_acreen1 {
            get {
                return ResourceManager.GetString("parameterization_acreen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Parameterization.
        /// </summary>
        internal static string parameterization_acreen2 {
            get {
                return ResourceManager.GetString("parameterization_acreen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Dynamic Properties.
        /// </summary>
        internal static string screen_dynprop {
            get {
                return ResourceManager.GetString("screen_dynprop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events.
        /// </summary>
        internal static string screen_events {
            get {
                return ResourceManager.GetString("screen_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events - Delete.
        /// </summary>
        internal static string screen_events_delete {
            get {
                return ResourceManager.GetString("screen_events_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events - Edit.
        /// </summary>
        internal static string screen_events_edit {
            get {
                return ResourceManager.GetString("screen_events_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Events - Insert.
        /// </summary>
        internal static string screen_events_insert {
            get {
                return ResourceManager.GetString("screen_events_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Funds.
        /// </summary>
        internal static string screen_funds {
            get {
                return ResourceManager.GetString("screen_funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string screen_topology {
            get {
                return ResourceManager.GetString("screen_topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology - Delete.
        /// </summary>
        internal static string screen_topology_delete {
            get {
                return ResourceManager.GetString("screen_topology_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology - Edit.
        /// </summary>
        internal static string screen_topology_edit {
            get {
                return ResourceManager.GetString("screen_topology_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology - Insert.
        /// </summary>
        internal static string screen_topology_insert {
            get {
                return ResourceManager.GetString("screen_topology_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Manage your application preferences.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a General Settings.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Topology.
        /// </summary>
        internal static string topology_input1 {
            get {
                return ResourceManager.GetString("topology_input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        internal static string topology_input2 {
            get {
                return ResourceManager.GetString("topology_input2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Class.
        /// </summary>
        internal static string topology_input3 {
            get {
                return ResourceManager.GetString("topology_input3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Indexer.
        /// </summary>
        internal static string topology_input4 {
            get {
                return ResourceManager.GetString("topology_input4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Product Class.
        /// </summary>
        internal static string topology_input5 {
            get {
                return ResourceManager.GetString("topology_input5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Select Topology.
        /// </summary>
        internal static string topology_input_null_text {
            get {
                return ResourceManager.GetString("topology_input_null_text", resourceCulture);
            }
        }
    }
}
