//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tipologia {

        public static global::System.Resources.ResourceManager resourceMan;

        public static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Tipologia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tipologia", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selecione a empresa abaixo para seguir..
        /// </summary>
        public static string field_1 {
            get {
                return ResourceManager.GetString("field_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string field_2 {
            get {
                return ResourceManager.GetString("field_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipologias Disponíveis.
        /// </summary>
        public static string Nav_1 {
            get {
                return ResourceManager.GetString("Nav_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipologia.
        /// </summary>
        public static string Nav_1_grid_col_1 {
            get {
                return ResourceManager.GetString("Nav_1_grid_col_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Nav_1_grid_col_2 {
            get {
                return ResourceManager.GetString("Nav_1_grid_col_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipologias Vinculadas.
        /// </summary>
        public static string Nav_2 {
            get {
                return ResourceManager.GetString("Nav_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipologia.
        /// </summary>
        public static string Nav_2_grid_col_1 {
            get {
                return ResourceManager.GetString("Nav_2_grid_col_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ações.
        /// </summary>
        public static string Nav_2_grid_col_2 {
            get {
                return ResourceManager.GetString("Nav_2_grid_col_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subtitle.
        /// </summary>
        public static string PageSubTitle {
            get {
                return ResourceManager.GetString("PageSubTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subtitle.
        /// </summary>
        public static string PageSubTitle_View {
            get {
                return ResourceManager.GetString("PageSubTitle_View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tipologia.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
