//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tutorial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tutorial() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tutorial", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string create_btn_1_tooltip {
            get {
                return ResourceManager.GetString("create_btn_1_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string create_btn_2_tooltip {
            get {
                return ResourceManager.GetString("create_btn_2_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Próximo Passo.
        /// </summary>
        internal static string create_btn_3_tooltip {
            get {
                return ResourceManager.GetString("create_btn_3_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Título.
        /// </summary>
        internal static string create_content_lbl_1 {
            get {
                return ResourceManager.GetString("create_content_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insira um título.
        /// </summary>
        internal static string create_content_lbl_1_placeholder {
            get {
                return ResourceManager.GetString("create_content_lbl_1_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string create_content_lbl_2 {
            get {
                return ResourceManager.GetString("create_content_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insira uma descrição.
        /// </summary>
        internal static string create_content_lbl_2_placeholder {
            get {
                return ResourceManager.GetString("create_content_lbl_2_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adicionar Vídeo.
        /// </summary>
        internal static string create_content_lbl_3 {
            get {
                return ResourceManager.GetString("create_content_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Utilizar URL de comparilhamento do YouTube. Exemplo: https://youtu.be/uBk9aYuI9V8.
        /// </summary>
        internal static string create_content_lbl_3_guide {
            get {
                return ResourceManager.GetString("create_content_lbl_3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a link do vídeo.
        /// </summary>
        internal static string create_content_lbl_3_placeholder {
            get {
                return ResourceManager.GetString("create_content_lbl_3_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adicionar Imagem.
        /// </summary>
        internal static string create_content_lbl_4 {
            get {
                return ResourceManager.GetString("create_content_lbl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione....
        /// </summary>
        internal static string create_content_lbl_4_placeholder {
            get {
                return ResourceManager.GetString("create_content_lbl_4_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conteúdo - Passo {0}.
        /// </summary>
        internal static string create_content_title {
            get {
                return ResourceManager.GetString("create_content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Módulo Associado.
        /// </summary>
        internal static string create_general_lbl_1 {
            get {
                return ResourceManager.GetString("create_general_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Autor.
        /// </summary>
        internal static string create_general_lbl_2 {
            get {
                return ResourceManager.GetString("create_general_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome do Tutorial.
        /// </summary>
        internal static string create_general_lbl_3 {
            get {
                return ResourceManager.GetString("create_general_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insira um nome.
        /// </summary>
        internal static string create_general_lbl_3_placeholder {
            get {
                return ResourceManager.GetString("create_general_lbl_3_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informações Principais.
        /// </summary>
        internal static string create_general_title {
            get {
                return ResourceManager.GetString("create_general_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Insira as informações do novo tutorial.
        /// </summary>
        internal static string create_sub_title {
            get {
                return ResourceManager.GetString("create_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Novo Tutorial.
        /// </summary>
        internal static string create_title {
            get {
                return ResourceManager.GetString("create_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string delete_btn_1_tooltip {
            get {
                return ResourceManager.GetString("delete_btn_1_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confirmar Exclusão.
        /// </summary>
        internal static string delete_btn_2 {
            get {
                return ResourceManager.GetString("delete_btn_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Confira e confirme a exclusão do tutorial selecionado.
        /// </summary>
        internal static string delete_sub_title {
            get {
                return ResourceManager.GetString("delete_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Deletar Tutorial.
        /// </summary>
        internal static string delete_title {
            get {
                return ResourceManager.GetString("delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string edit_btn_1_tooltip {
            get {
                return ResourceManager.GetString("edit_btn_1_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string edit_btn_2_tooltip {
            get {
                return ResourceManager.GetString("edit_btn_2_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adicionar Passo.
        /// </summary>
        internal static string edit_btn_3_tooltip {
            get {
                return ResourceManager.GetString("edit_btn_3_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Título.
        /// </summary>
        internal static string edit_content_lbl_1 {
            get {
                return ResourceManager.GetString("edit_content_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Descrição.
        /// </summary>
        internal static string edit_content_lbl_2 {
            get {
                return ResourceManager.GetString("edit_content_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adicionar Vídeo.
        /// </summary>
        internal static string edit_content_lbl_3 {
            get {
                return ResourceManager.GetString("edit_content_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Utilizar URL de comparilhamento do YouTube. Exemplo: https://youtu.be/uBk9aYuI9V8.
        /// </summary>
        internal static string edit_content_lbl_3_guide {
            get {
                return ResourceManager.GetString("edit_content_lbl_3_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a link do vídeo.
        /// </summary>
        internal static string edit_content_lbl_3_placeholder {
            get {
                return ResourceManager.GetString("edit_content_lbl_3_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Adicionar Imagem.
        /// </summary>
        internal static string edit_content_lbl_4 {
            get {
                return ResourceManager.GetString("edit_content_lbl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Selecione....
        /// </summary>
        internal static string edit_content_lbl_4_placeholder {
            get {
                return ResourceManager.GetString("edit_content_lbl_4_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Conteúdo - Passo {0}.
        /// </summary>
        internal static string edit_content_title {
            get {
                return ResourceManager.GetString("edit_content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Módulo Associado.
        /// </summary>
        internal static string edit_general_lbl_1 {
            get {
                return ResourceManager.GetString("edit_general_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Autor.
        /// </summary>
        internal static string edit_general_lbl_2 {
            get {
                return ResourceManager.GetString("edit_general_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome do Tutorial.
        /// </summary>
        internal static string edit_general_lbl_3 {
            get {
                return ResourceManager.GetString("edit_general_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Informações Principais.
        /// </summary>
        internal static string edit_general_title {
            get {
                return ResourceManager.GetString("edit_general_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Altere as informações do tutorial.
        /// </summary>
        internal static string edit_sub_title {
            get {
                return ResourceManager.GetString("edit_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Editar Tutorial.
        /// </summary>
        internal static string edit_title {
            get {
                return ResourceManager.GetString("edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Novo Tutorial.
        /// </summary>
        internal static string index_btn_1 {
            get {
                return ResourceManager.GetString("index_btn_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Nome Tutorial.
        /// </summary>
        internal static string index_col_1 {
            get {
                return ResourceManager.GetString("index_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Autor.
        /// </summary>
        internal static string index_col_2 {
            get {
                return ResourceManager.GetString("index_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string index_col_3 {
            get {
                return ResourceManager.GetString("index_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Passos.
        /// </summary>
        internal static string index_col_4 {
            get {
                return ResourceManager.GetString("index_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pesquisar Tutorial.
        /// </summary>
        internal static string index_search {
            get {
                return ResourceManager.GetString("index_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Veja aqui todos os tutoriais disponíveis.
        /// </summary>
        internal static string index_sub_title {
            get {
                return ResourceManager.GetString("index_sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tutoriais.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        internal static string view_btn_1_tooltip {
            get {
                return ResourceManager.GetString("view_btn_1_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Visualizando {0}.
        /// </summary>
        internal static string view_sub_title {
            get {
                return ResourceManager.GetString("view_sub_title", resourceCulture);
            }
        }
    }
}
