//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Widgets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Widgets() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Widgets", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contract Administration.
        /// </summary>
        internal static string admin_contracts_1 {
            get {
                return ResourceManager.GetString("admin_contracts_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Contracts.
        /// </summary>
        internal static string admin_contracts_2 {
            get {
                return ResourceManager.GetString("admin_contracts_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Active.
        /// </summary>
        internal static string admin_contracts_lbl_1 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Suspended.
        /// </summary>
        internal static string admin_contracts_lbl_2 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Due date 90 days.
        /// </summary>
        internal static string admin_contracts_lbl_3 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closed.
        /// </summary>
        internal static string admin_contracts_lbl_4 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Judiciary.
        /// </summary>
        internal static string admin_contracts_lbl_5 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string admin_contracts_lbl_6 {
            get {
                return ResourceManager.GetString("admin_contracts_lbl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Whistleblower Clause.
        /// </summary>
        internal static string clausula_1 {
            get {
                return ResourceManager.GetString("clausula_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Market.
        /// </summary>
        internal static string currency_1 {
            get {
                return ResourceManager.GetString("currency_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Financial Market.
        /// </summary>
        internal static string currency_2 {
            get {
                return ResourceManager.GetString("currency_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Documents.
        /// </summary>
        internal static string documents_1 {
            get {
                return ResourceManager.GetString("documents_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Documents.
        /// </summary>
        internal static string documents_2 {
            get {
                return ResourceManager.GetString("documents_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Issuance of Contracts.
        /// </summary>
        internal static string emissao_contracts_1 {
            get {
                return ResourceManager.GetString("emissao_contracts_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Issuance of Contracts.
        /// </summary>
        internal static string emissao_contracts_2 {
            get {
                return ResourceManager.GetString("emissao_contracts_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Messages.
        /// </summary>
        internal static string messages_1 {
            get {
                return ResourceManager.GetString("messages_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pendencies.
        /// </summary>
        internal static string pending_1 {
            get {
                return ResourceManager.GetString("pending_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Pendencies.
        /// </summary>
        internal static string pending_2 {
            get {
                return ResourceManager.GetString("pending_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Closure.
        /// </summary>
        internal static string pending_lbl_1 {
            get {
                return ResourceManager.GetString("pending_lbl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Update.
        /// </summary>
        internal static string pending_lbl_2 {
            get {
                return ResourceManager.GetString("pending_lbl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Price.
        /// </summary>
        internal static string pending_lbl_3 {
            get {
                return ResourceManager.GetString("pending_lbl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Organize your work tools here.
        /// </summary>
        internal static string sub_title {
            get {
                return ResourceManager.GetString("sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Widgets.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
